### PR TITLE
Fix semantics of `not_` applied over `&&.` and `||.`

### LINKED ISSUE #359: `not_` is broken
```haskell
share [mkPersist sqlSettings] [persistLowerCase|
  Person
    name String
    age Int
    deriving Eq Show
|]

query :: SqlPersistM [Entity Person]
query = select $ from \(person :: SqlExpr (Entity Person)) -> do
  where_ $ not_ (person.name !=. val "foo" &&. person.age >. val @Int 15)
  pure person
```
produces
```sql
SELECT "person"."id", "person"."name", "person"."age" FROM "person" WHERE NOT ("person"."name" != ?) AND ("person"."age" > ?); 
```
expected
```sql
SELECT "person"."id", "person"."name", "person"."age" FROM "person" WHERE NOT (("person"."name" != ?) AND ("person"."age" > ?)); 
```

### PR DESCRIPTION
**Pull request by blujupiter32**
This PR fixes #359 by always wrapping arguments to `not_` in parentheses when building SQL queries. Some tests combining `not_` with `&&.` and `||.` have also been added to `Common.Test`.

This is technically a breaking change: `not_ (x &&. y)` is no longer equivalent to `(not_ x) &&. y`, for example, although the equivalence is probably unintended.

---

Before submitting your PR, check that you've:

- [ ] Bumped the version number.
- [x] Ran `stylish-haskell` and otherwise adhered to the [style guide](https://github.com/bitemyapp/esqueleto/blob/master/style-guide.yaml).
  - `stylish-haskell` fails to parse the `DEPRECATED` pragma for `sub_select` in `Database.Esqueleto.Internal.Internal`.

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR.
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts).

### CODE REVIEW

**Comment by parsonsmatt** [comment]
This is great work, thank you! I apologize for not merging and releasing earlier. I believe this should be a patch version bump, so I will release asap.

File: test/Common/Test.hs [hunk 1]
```diff
@@ -921,6 +911,44 @@ testSelectWhere = describe "select where_" $ do
                         , val $ PointKey 5 6 )
                 asserting $ ret `shouldBe` [()]
 
+    describe "when using not_" $ do
```
Comment (parsonsmatt) [inline test/Common/Test.hs:914]:
```suggestion
    describe "when using not_" $ do
        itDb "works for a single expression" $ do
            ret <-
                select $
                pure $ not_ $ val True
            asserting $ do
                ret `shouldBe` [Value False]

```

Comment (parsonsmatt) [reply test/Common/Test.hs:914]: wanted to add one more test for the solo case

**Review by parsonsmatt — APPROVED** [review]

**Comment by parsonsmatt** [comment]
Tested this on the work repo, only one failure relating to a golden test. Thanks!
